### PR TITLE
Update Item.js

### PR DESCRIPTION
**Pull request by lvenier**
parseInt incase of String used on constructor

### CODE REVIEW

**Comment by lvenier** [comment]
@olragon : can you tell me if you this one makes sense ?

**Comment by olragon** [comment]
@lvenier length can be decimal, we should use `Number()`. If we use typecasting here, we should validate if it's a real number instead of NaN. If you make changes, please add some tests.

**Comment by lvenier** [comment]
ok will do.
Question : do we remove the item of the list if a value is not a parsable number ?

can you also tell mw how to test ?
I ran ```npm run build && npm run test``` but it looks it is not enough to run the test.

**Comment by olragon** [comment]
@lvenier you can run the test by the [command](https://github.com/olragon/binpackingjs/blob/master/package.json#L13) `npm run test`.
About the question, for now, I think you should handle these requirements outside of `binpackingjs`.
In the long run, `binpackingjs` should be rewritten using TypeScript, handle arguments validation and split 2D & 3D part separately.

**Pull request closed without merging**
